import {
  ArrowLeft,
  ArrowRight,
  Check,
  CheckCheck,
  Command,
  Copy,
  ExternalLink,
  Pencil,
  Plus,
  RefreshCw,
  SearchCheck,
  Settings,
  SquareArrowOutUpRight,
  Star,
  Tag,
  Trash2,
  X,
  type LucideIcon,
} from "lucide-react";
import type { ActionId } from "@/lib/actions";

/** Lucide only, and one per action, so the two renderers cannot illustrate the same action differently. */
export const ACTION_ICON: Record<ActionId, LucideIcon> = {
  open: SquareArrowOutUpRight,
  openAniList: ExternalLink,
  copySelection: Copy,
  addToList: Plus,
  edit: Pencil,
  plusOne: Plus,
  plusVolume: Plus,
  complete: CheckCheck,
  setStatus: Tag,
  setScore: Star,
  removeFromList: Trash2,
  scrobbleNow: Check,
  scrobbleCancel: X,
  fixMatch: SearchCheck,
  clearOverride: RefreshCw,
  back: ArrowLeft,
  forward: ArrowRight,
  reload: RefreshCw,
  palette: Command,
  settings: Settings,
};
