// `cargo test` regenerates `src/api/bindings.ts` from the command signatures; verify.mjs fails when git then sees a diff.
#[test]
fn export_bindings() {
    use specta_typescript::Typescript;
    let ts = Typescript::default()
        .header("// Generated by `cargo test` from the Rust command signatures; never edited by hand, see CLAUDE.md.");
    karasu_lib::specta_builder()
        .export(ts, "../src/api/bindings.ts")
        .expect("the bindings export");
}
